name: Publish to PyPI
on: push

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: setup python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install setuptools
      run: >-
        python -m
        pip install
        setuptools
        --user
    - name: Build sdist
      run: >-
        python
        setup.py sdist
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    
